from __future__ import annotations

import os
import csv
import json
from datetime import datetime

from airflow import DAG
from airflow.models import Variable
from airflow.operators.python import PythonOperator
from airflow.providers.amazon.aws.hooks.s3 import S3Hook
import snowflake.connector

DEFAULT_ARGS = {
    "owner": "airflow",
    "retries": 1,
}

# Path to the geocoded JSON checkpoint file
# This is the schools_geocode_checkpoint.json generated by geocode_schools.py
CHECKPOINT_FILE = "/opt/airflow/dags/schools_geocode_checkpoint.json"
OUTPUT_CSV      = "/opt/airflow/dags/schools_geocoded.csv"


def read_checkpoint_and_convert(**context):
    """Read the geocoded checkpoint JSON and convert to CSV."""

    if not os.path.exists(CHECKPOINT_FILE):
        raise FileNotFoundError(f"Checkpoint file not found at {CHECKPOINT_FILE}. "
                                f"Run geocode_schools.py first.")

    print(f"Reading checkpoint from {CHECKPOINT_FILE}")
    with open(CHECKPOINT_FILE, "r") as f:
        checkpoint = json.load(f)

    print(f"Found {len(checkpoint)} geocoded school records")

    # Write to CSV
    fieldnames = ["SCHID", "LAT", "LONG", "GEOCODE_STATUS"]
    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for schid, data in checkpoint.items():
            writer.writerow({
                "SCHID":          schid,
                "LAT":            data.get("lat", -999.0),
                "LONG":           data.get("long", -999.0),
                "GEOCODE_STATUS": data.get("status", "UNKNOWN")
            })

    geocoded = sum(1 for v in checkpoint.values() if v.get("status") == "GEOCODED")
    failed   = sum(1 for v in checkpoint.values() if v.get("status") == "FAILED")
    print(f"CSV written to {OUTPUT_CSV} — {geocoded} geocoded, {failed} failed")

    context["task_instance"].xcom_push(key="csv_path", value=OUTPUT_CSV)
    return {"record_count": len(checkpoint), "geocoded": geocoded, "failed": failed}


def upload_to_s3(**context):
    """Upload geocoded CSV to S3."""
    s3_bucket   = Variable.get("boston_s3_bucket")
    aws_conn_id = Variable.get("boston_aws_conn_id", default_var="aws_default")

    ti       = context["task_instance"]
    csv_path = ti.xcom_pull(task_ids="read_checkpoint_and_convert", key="csv_path")

    if not csv_path or not os.path.exists(csv_path):
        raise FileNotFoundError(f"CSV file not found at {csv_path}")

    s3_key = "schools/schools_geocoded.csv"
    print(f"Uploading {csv_path} to s3://{s3_bucket}/{s3_key}")

    hook = S3Hook(aws_conn_id=aws_conn_id)
    hook.load_file(
        filename=csv_path,
        key=s3_key,
        bucket_name=s3_bucket,
        replace=True
    )

    print(f"Successfully uploaded to S3: s3://{s3_bucket}/{s3_key}")

    context["task_instance"].xcom_push(key="s3_key",    value=s3_key)
    context["task_instance"].xcom_push(key="s3_bucket", value=s3_bucket)

    return s3_key


def create_snowflake_table(**context):
    """Create STG_BOSTON_SCHOOLS_GEOCODED table in Snowflake STAGE schema."""
    conn = snowflake.connector.connect(
        account=os.environ["SNOWFLAKE_ACCOUNT"],
        user=os.environ["SNOWFLAKE_USER"],
        password=os.environ["SNOWFLAKE_PASSWORD"],
        warehouse=os.environ["SNOWFLAKE_WAREHOUSE"],
        database=os.environ["SNOWFLAKE_DATABASE"],
        schema=os.environ["SNOWFLAKE_SCHEMA"],
        role=os.environ["SNOWFLAKE_ROLE"],
        insecure_mode=True
    )

    create_table_sql = """
    CREATE TABLE IF NOT EXISTS NEIGHBOURWISE_DOMAINS.STAGE.STG_BOSTON_SCHOOLS_GEOCODED (
        SCHID           INTEGER,
        LAT             FLOAT,
        LONG            FLOAT,
        GEOCODE_STATUS  VARCHAR(20),
        LOAD_TIMESTAMP  TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    );
    """

    try:
        cursor = conn.cursor()
        print("Creating table STG_BOSTON_SCHOOLS_GEOCODED")
        cursor.execute(create_table_sql)
        print("Table created or already exists")
        return "Table ready"
    finally:
        cursor.close()
        conn.close()


def load_s3_to_snowflake(**context):
    """Truncate and reload STG_BOSTON_SCHOOLS_GEOCODED from S3."""
    ti        = context["task_instance"]
    s3_bucket = ti.xcom_pull(task_ids="upload_to_s3", key="s3_bucket")
    s3_key    = ti.xcom_pull(task_ids="upload_to_s3", key="s3_key")

    from airflow.hooks.base import BaseHook
    aws_conn       = BaseHook.get_connection("aws_default")
    aws_access_key = aws_conn.login
    aws_secret_key = aws_conn.password

    s3_path = f"s3://{s3_bucket}/{s3_key}"

    conn = snowflake.connector.connect(
        account=os.environ["SNOWFLAKE_ACCOUNT"],
        user=os.environ["SNOWFLAKE_USER"],
        password=os.environ["SNOWFLAKE_PASSWORD"],
        warehouse=os.environ["SNOWFLAKE_WAREHOUSE"],
        database=os.environ["SNOWFLAKE_DATABASE"],
        schema=os.environ["SNOWFLAKE_SCHEMA"],
        role=os.environ["SNOWFLAKE_ROLE"],
        insecure_mode=True
    )

    try:
        cursor = conn.cursor()
        cursor.execute("USE SCHEMA NEIGHBOURWISE_DOMAINS.STAGE")

        print("Truncating STG_BOSTON_SCHOOLS_GEOCODED")
        cursor.execute("TRUNCATE TABLE NEIGHBOURWISE_DOMAINS.STAGE.STG_BOSTON_SCHOOLS_GEOCODED")

        copy_sql = f"""
        COPY INTO NEIGHBOURWISE_DOMAINS.STAGE.STG_BOSTON_SCHOOLS_GEOCODED
            (SCHID, LAT, LONG, GEOCODE_STATUS)
        FROM '{s3_path}'
        CREDENTIALS = (
            AWS_KEY_ID = '{aws_access_key}'
            AWS_SECRET_KEY = '{aws_secret_key}'
        )
        FILE_FORMAT = (
            TYPE = 'CSV'
            FIELD_DELIMITER = ','
            SKIP_HEADER = 1
            FIELD_OPTIONALLY_ENCLOSED_BY = '"'
            TRIM_SPACE = TRUE
            ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
            NULL_IF = ('NULL', 'null', '')
        )
        ON_ERROR = 'CONTINUE'
        PURGE = FALSE;
        """

        print(f"Loading from {s3_path}")
        cursor.execute(copy_sql)

        cursor.execute("""
            SELECT GEOCODE_STATUS, COUNT(*)
            FROM NEIGHBOURWISE_DOMAINS.STAGE.STG_BOSTON_SCHOOLS_GEOCODED
            GROUP BY GEOCODE_STATUS
        """)
        for row in cursor.fetchall():
            print(f"  {row[0]}: {row[1]} records")

        cursor.execute("SELECT COUNT(*) FROM NEIGHBOURWISE_DOMAINS.STAGE.STG_BOSTON_SCHOOLS_GEOCODED")
        count = cursor.fetchone()[0]
        print(f"Total records loaded: {count}")

        return {"status": "success", "records_loaded": count}

    except Exception as e:
        print(f"Error loading data: {str(e)}")
        raise
    finally:
        cursor.close()
        conn.close()


with DAG(
    dag_id="schools_geocoded_to_s3_to_snowflake",
    default_args=DEFAULT_ARGS,
    start_date=datetime(2026, 2, 27),
    schedule_interval=None,   # Manual trigger only — runs once after geocoding
    catchup=False,
    tags=["boston", "schools", "geocoding", "reference"],
) as dag:

    read_checkpoint_task = PythonOperator(
        task_id="read_checkpoint_and_convert",
        python_callable=read_checkpoint_and_convert,
        provide_context=True,
    )

    upload_task = PythonOperator(
        task_id="upload_to_s3",
        python_callable=upload_to_s3,
        provide_context=True,
    )

    create_table_task = PythonOperator(
        task_id="create_snowflake_table",
        python_callable=create_snowflake_table,
        provide_context=True,
    )

    load_to_snowflake_task = PythonOperator(
        task_id="load_to_snowflake",
        python_callable=load_s3_to_snowflake,
        provide_context=True,
    )

    read_checkpoint_task >> upload_task >> create_table_task >> load_to_snowflake_task